#:kivy 2.0

<BookingScreen>:
    GridLayout:
        rows: 10
        pos_hint: {'center_x' : .5, 'center_y': .5}  
        size_hint: None, None
        size: root.width * .5, root.width * .5

        MDLabel:
            id: results

        MDTextField:
            id: repoUrl
            hint_text: 'Enter the clone URL for the remote repository'

        GridLayout:
            cols: 2
            AnchorLayout:
                anchor_x: 'left'
                MDFillRoundFlatButton:
                    font_size: "18sp"
                    text: 'Select Date'
                    on_release: app.show_date_picker()
                    pos_hint: {'center_x': .5, 'center_y': .5}

            AnchorLayout:  
                anchor_x: 'right'  
                MDLabel:
                    font_size: "20sp"
                    id: date
                    text: 'No date chosen'
                    halign: 'right'

        BoxLayout:
            orientation: 'horizontal'
            MDLabel:
                text: ' '
            MDLabel:
                font_size: "20sp"
                text: 'Small'
            CheckBox:
                color: 255, 255, 255, 1
                id: roomSize
                group: 'size'
                on_active: app.on_checkbox_active(self, self.active, "SMALL")
            MDLabel:
                text: ' '
            MDLabel:
                font_size: "20sp"
                text: 'Large'
            CheckBox:
                color: 255, 255, 255, 1
                id: roomSize
                group: 'size'
                on_active: app.on_checkbox_active(self, self.active, "LARGE")
            MDLabel:
                text: ' '


        TextInput:
            id: roomNumber
            hint_text: 'Room #: '

        GridLayout:
            cols: 2
            AnchorLayout:
                anchor_x: 'left'
                MDFillRoundFlatButton:
                    font_size: "18sp"
                    text: 'Select Time'
                    on_release: app.show_time_picker()
                    pos_hint: {'center_x': .5, 'center_y': .5}

            AnchorLayout:  
                anchor_x: 'right'  
                MDLabel:
                    font_size: "20sp"
                    id: time
                    text: 'No time chosen'
                    halign: 'right'

        Button:
            id: submit
            text: 'Submit'
            on_press: app.bookRoom(roomSize.text, time.text, roomNumber.text, date.text, repoUrl.text)



 



