#:kivy 2.0

<BookingScreen>:
    GridLayout:
        rows: 10
        pos_hint: {'center_x' : .5, 'center_y': .5}  
        size_hint: None, None
        size: root.width * .5, root.width * .5

        GridLayout:
            cols: 2
            AnchorLayout:
                anchor_x: 'left'
                MDRaisedButton:
                    text: 'Select Date'
                    on_release: app.show_date_picker()
                    pos_hint: {'center_x': .5, 'center_y': .5}

            AnchorLayout:  
                anchor_x: 'right'  
                MDLabel:
                    id: date
                    text: 'No date chosen'
                    halign: 'right'

        TextInput:
            id: roomSize
            hint_text: 'Room Size: [LARGE or SMALL]'

        TextInput:
            id: roomNumber
            hint_text: 'Room #: '

        GridLayout:
            cols: 2
            AnchorLayout:
                anchor_x: 'left'
                MDRaisedButton:
                    text: 'Select Time'
                    on_release: app.show_time_picker()
                    pos_hint: {'center_x': .5, 'center_y': .5}

            AnchorLayout:  
                anchor_x: 'right'  
                MDLabel:
                    id: time
                    text: 'No time chosen'
                    halign: 'right'

        Button:
            id: submit
            text: 'Submit'
            on_press: app.bookRoom(roomSize.text, time.text, roomNumber.text, date.text)



 



